Add a ccnd test having 3 ccnds in a chain with a 4th in a spur off the center one
refs #70

diff --git a/ccnd/tests/functions b/ccnd/tests/functions
--- a/ccnd/tests/functions
+++ b/ccnd/tests/functions
@@ -8,7 +8,23 @@ AFTER () {
   : Used by testdriver for determining test order
 }
 
+Fail () {
+  echo "***" Failing $TESTNAME - $*
+  exit 1
+}
+
 SkipTest () {
   echo "***" Skipping $TESTNAME - $*
   exit 9
+}
+
+WithCCND () {
+  local port;
+  port=$((CCN_LOCAL_PORT_BASE+$1))
+  shift
+  CCN_LOCAL_PORT=$port "$@"
+}
+
+RunTest () {
+  ( . settings; . functions; . $1 )
 }
